autofit-larger=100%X100%
panscan=1.0
autocreate-playlist=same
directory-mode=ignore
loop-playlist=inf
loop-file=inf
reset-on-next-file=window-scale,video-zoom,video-rotate,video-align-x,video-align-y,video-aspect-override,video-pan-x,video-pan,y,panscan

[image-settings]
profile-cond=p["current-tracks/video/image"]
vo=x11
force-window=no
