#!/usr/bin/env sh

# Directory where to store temporary data
TMP_DIR="/tmp/rmpc"

# Ensure the directory is created
mkdir -p "$TMP_DIR"

# Where to temporarily store the album art received from rmpc
ALBUM_ART_PATH="$TMP_DIR/notification_cover"

# Path to fallback album art if no album art is found by rmpc/mpd
# Change this to your needs
DEFAULT_ALBUM_ART_PATH="$HOME/Pictures/ininia-birthday.png"

# Save album art of the currently playing song to a file
if ! rmpc albumart --output "$ALBUM_ART_PATH"; then
    # Use default album art if rmpc returns non-zero exit code
    ALBUM_ART_PATH="${DEFAULT_ALBUM_ART_PATH}"
fi

# Gets current playing status
STATE=$(rmpc status | jq -r '.state')

# Send the notification
if [ "$STATE" = "Play" ]; then
    notify-send -i "${ALBUM_ART_PATH}" "Now ${STATE}ing" "$ARTIST\n$TITLE"
else
    notify-send -i "${ALBUM_ART_PATH}" "${STATE}d" "$ARTIST\n$TITLE"
fi
