id = 677226551607033903
hosts = ["127.0.0.1:6600"]

[format]
details = "$title"
state = "$albumartist // $album"
timestamp = "both"
large_image = "notes"
small_image = "notes"
large_text = ""
small_text = ""
display_type = "state"
button1_text = ""
button1_link = ""
button2_text = ""
button2_link = ""
