#! /usr/bin/env zsh
current_theme=$(gsettings get org.gnome.desktop.interface gtk-theme)

# opens foot in proper dark or light theme
if [ "${current_theme}" = "'adw-gtk3'" ]; then
    foot -o initial-color-theme=light &
else
    foot -o initial-color-theme=dark &
fi
