#! /usr/bin/env zsh
current_theme=$(gsettings get org.gnome.desktop.interface gtk-theme)

if [ "${current_theme}" = "'Adwaita-light'" ]; then
    awww img ~/Pictures/Wallpapers/dark-pink-topo.png -t none &
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    gsettings set org.gnome.desktop.interface icon-theme 'arcticons-dark'
    sed -i 's/light/dark/' ~/.local/state/noctalia/settings.toml
    sed -i 's/active-color "#333333"/active-color "#bd5a6f"/' ~/.config/niri/cfg/layout.kdl
    sed -i 's/color "#000000CC"/color "#bd5a6fCC"/' ~/.config/niri/cfg/rules.kdl
    sed -i 's/#f8b4c9/#070707/' ~/.config/gtk-3.0/gtk.css
    sed -i 's/e-pink/e-pink-dark/' ~/.config/fuzzel/fuzzel.ini
    sed -i 's/e-pink/e-pink-dark/' ~/.config/btop/btop.conf
    sed -i 's/peachpuff/shades-of-pink-dark/' ~/.config/helix/config.toml
    pkill -USR1 foot
    pkill -SIGUSR2 btop
elif [ "${current_theme}" = "'Adwaita'" ]; then
    awww img ~/Pictures/Wallpapers/pinkswirls.jpg -t none &
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-light'
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    gsettings set org.gnome.desktop.interface icon-theme 'arcticons-light'
    sed -i 's/dark/light/' ~/.local/state/noctalia/settings.toml
    sed -i 's/active-color "#bd5a6f"/active-color "#333333"/' ~/.config/niri/cfg/layout.kdl
    sed -i 's/color "#bd5a6fCC"/color "#000000CC"/' ~/.config/niri/cfg/rules.kdl
    sed -i 's/#070707/#f8b4c9/' ~/.config/gtk-3.0/gtk.css
    sed -i 's/e-pink-dark/e-pink/' ~/.config/fuzzel/fuzzel.ini
    sed -i 's/e-pink-dark/e-pink/' ~/.config/btop/btop.conf
    sed -i 's/shades-of-pink-dark/peachpuff/' ~/.config/helix/config.toml
    pkill -USR2 foot
    pkill -SIGUSR2 btop
fi
