#! /usr/bin/env zsh
color_scheme=$(gsettings get org.gnome.desktop.interface color-scheme)

if [ "${color_scheme}" = "'prefer-light'" ]; then
    awww img ~/Pictures/Wallpapers/dark-pink-topo.png -t none &
    gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    gsettings set org.gnome.desktop.interface icon-theme 'arcticons-dark'
    noctalia msg theme-mode-set dark
    cp ~/.config/noctalia/config.toml.sop-dark ~/.config/noctalia/config.toml
    cp ~/.config/niri/cfg/layout.kdl.sop-dark ~/.config/niri/cfg/layout.kdl
    cp ~/.config/niri/cfg/rules.kdl.sop-dark ~/.config/niri/cfg/rules.kdl
    sed -i 's/sop-light/sop-dark/' ~/.config/fuzzel/fuzzel.ini
    sed -i 's/sop-light/sop-dark/' ~/.config/btop/btop.conf
    pkill -USR1 foot
    pkill -SIGUSR2 btop
elif [ "${color_scheme}" = "'prefer-dark'" ]; then
    awww img ~/Pictures/Wallpapers/pinkswirls.jpg -t none &
    gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    gsettings set org.gnome.desktop.interface icon-theme 'arcticons-light'
    noctalia msg theme-mode-set light
    cp ~/.config/noctalia/config.toml.sop-light ~/.config/noctalia/config.toml
    cp ~/.config/niri/cfg/layout.kdl.sop-light ~/.config/niri/cfg/layout.kdl
    cp ~/.config/niri/cfg/rules.kdl.sop-light ~/.config/niri/cfg/rules.kdl
    sed -i 's/sop-dark/sop-light/' ~/.config/fuzzel/fuzzel.ini
    sed -i 's/sop-dark/sop-light/' ~/.config/btop/btop.conf
    pkill -USR2 foot
    pkill -SIGUSR2 btop
fi
