#! /usr/bin/env zsh
current_theme=$(gsettings get org.gnome.desktop.interface gtk-theme)

if [ "${current_theme}" = "'Adwaita-light'" ]; then
    awww img ~/Pictures/Wallpapers/dark-pink-topo.png -t none &
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    gsettings set org.gnome.desktop.interface icon-theme 'arcticons-dark'
    sed -i 's/light/dark/' ~/.local/state/noctalia/settings.toml
    cp ~/.config/niri/cfg/layout.kdl.sop-dark ~/.config/niri/cfg/layout.kdl
    cp ~/.config/niri/cfg/rules.kdl.sop-dark ~/.config/niri/cfg/rules.kdl
    sed -i 's/#f8b4c9/#070707/' ~/.config/gtk-3.0/gtk.css
    sed -i 's/sop-light/sop-dark/' ~/.config/fuzzel/fuzzel.ini
    sed -i 's/sop-light/sop-dark/' ~/.config/btop/btop.conf
    pkill -USR1 foot
    pkill -SIGUSR2 btop
elif [ "${current_theme}" = "'Adwaita'" ]; then
    awww img ~/Pictures/Wallpapers/pinkswirls.jpg -t none &
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-light'
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    gsettings set org.gnome.desktop.interface icon-theme 'arcticons-light'
    sed -i 's/dark/light/' ~/.local/state/noctalia/settings.toml
    cp ~/.config/niri/cfg/layout.kdl.sop-light ~/.config/niri/cfg/layout.kdl
    cp ~/.config/niri/cfg/rules.kdl.sop-light ~/.config/niri/cfg/rules.kdl
    sed -i 's/#070707/#f8b4c9/' ~/.config/gtk-3.0/gtk.css
    sed -i 's/sop-dark/sop-light/' ~/.config/fuzzel/fuzzel.ini
    sed -i 's/sop-dark/sop-light/' ~/.config/btop/btop.conf
    pkill -USR2 foot
    pkill -SIGUSR2 btop
fi
