[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.4
    start = [ "workspaces", "clock_date", "clock_time" ]
    center = [
        "cat",
        "spiral",
        "audio_visualizer",
        "heart",
        "media",
        "heart",
        "audio_visualizer",
        "spiral",
        "cat_2"
    ]
    end = [ "recorder", "weather", "cpu", "temp", "battery" ]
    font_weight = 400
    margin_edge = 0
    margin_ends = 40
    radius = 0
    scale = 1.25
    shadow = false
    widget_spacing = 16

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "clipboard"

[desktop_widgets]
enabled = false

[location]
address = ""
auto_locate = true

[notification]
background_opacity = 0.4999999888241291
show_app_name = false

[osd]
orientation = "horizontal"
position = "top_center"

    [osd.kinds]
    media = false

[plugin_settings."noctalia/screen_recorder"]
hide_inactive = true

[plugins]
enabled = [ "noctalia/bongocat", "noctalia/screen_recorder" ]

[shell]
avatar_path = "~/Pictures/Wallpapers/persona1.jpg"
clipboard_history_max_entries = 25
corner_radius_scale = 0.0
date_format = "%A, %B %d"
font_family = "Maple Mono NF"
polkit_agent = true
settings_show_advanced = true
show_location = false
telemetry_enabled = false
time_format = "%I:%M"
ui_scale = 1.2000000104308128

    [shell.animation]
    enabled = false

    [shell.panel]
    clipboard_placement = "attached"
    launcher_categories = false
    launcher_compact = true
    launcher_show_icons = false
    shadow = false

    [shell.shadow]
    blur = 1
    offset_x = 5
    offset_y = 5

[theme]
builtin = "Noctalia"
community_palette = "Noctalia Legacy"
custom_palette = "Shades of Pink"
source = "custom"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4" ]
    enable_builtin_templates = true
    enable_community_templates = false

[wallpaper]
directory = "~/Pictures/Wallpapers"
enabled = false
fill_mode = "stretch"
transition = [ "fade" ]
transition_on_startup = true

    [wallpaper.default]
    path = "~/Pictures/Wallpapers/light-topo.png"

    [wallpaper.last]
    path = "~/Pictures/Wallpapers/light-topo.png"

    [wallpaper.monitors.eDP-1]
    path = "~/Pictures/Wallpapers/light-topo.png"

[weather]
address = ""
refresh_minutes = 15
unit = "imperial"

[widget.audio_visualizer]
bands = 64
scale = 1.25
width = 160.0

[widget.battery]
display_mode = "graphic"

[widget.cat]
input_device = "/dev/input/event11"
scale = 1.75
type = "noctalia/bongocat:cat"

[widget.cat_2]
input_device = "/dev/input/event11"
scale = 1.75
type = "noctalia/bongocat:cat"

[widget.clock_date]
format = "%A, %B %d"
type = "clock"

[widget.clock_time]
format = "%I:%M:%S%P"
type = "clock"

[widget.cpu]
display = "text"

[widget.spiral]
font_family = "Maple Mono NF"
glyph = "spiral"
icon_color = "on_surface"
scale = 1.3999999999999999
type = "custom_button"

[widget.heart]
font_family = "Maple Mono NF"
glyph = "heart"
scale = 1.3999999999999999
type = "custom_button"

[widget.media]
art_size = 20.0
title_scroll = "always"

[widget.network]
show_label = false

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.temp]
display = "text"
show_label = false

[widget.weather]
show_condition = true

[widget.workspaces]
capsule_radius = 0
display = "none"
empty_color = "on_tertiary"
hide_when_empty = true
occupied_color = "tertiary"
